name: Deploy

on:
  schedule:
    # 毎日 8 時
    - cron: '0 8 * * *'


  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
